################################
# Author: Gaurav Singhal
# e-mail: gs.singhal@gmail.com
# Collaborators:
#	Dr Laurence E. Day
#	Pranav Ramkumar
#	Dr Mack Ramachandran
#################################

#### Used R libraries ####
#library(dplyr)
#library(Matrix)
# #For utilities
# library(intergraph)
# #For generation
# library(xtable)
# library(MCMCpack)
# library(extraDistr)
# library(predictionet)
# #for optimization
# library(nleqslv)
# library(nloptr)
# #For propagation
# library(doParallel)
# library(bigmemory)

library(MASS)
library(igraph)
detach("package:igraph")
library(network)
library(sna)

library(modules)
library(here)

#### Functions to generate Ntwk #####

generate <- modules::use(here::here("app/src/Generate.R"))
#### Functions to perform essential computations on Ntwk ####
addNode <- modules::use(here::here("app/src/AddNode.R"))

traverse <- modules::use(here::here("app/src/Traverse.R"))

propagate <- modules::use(here::here("app/src/Propagate.R"))

#### Generate Example Graph ####
peri <- generate$buildCorePeri(N = 100, K = 10)
rslt <- generate$initializeSheets(peri, K = 10, A0 = 10000)

rslt0 <- traverse$calcRiskArray(rslt[[2]])
risk.array <- rslt0[[1]]
ntwk <- rslt0[[2]]
rm(rslt)

#### Add Node ####
rslt <- addNode$addNode2Ntwk(ntwk,risk.array,750,
                             out.DF=data.frame(list(nodes=c(1,2,3,4), #this dataframe would be input by UI
                                                    names=c('Mack','Gaurav','Laurence','Pranav'),
                                                    trust=c(325,225,175,275))))

ntwk <- rslt$ntwk
risk.array <- rslt$risk.array
rm(rslt)
##### Borrow Funds/Propogate Loan ####

#borrowing potential of node X1 -
##NOTE: We can have this stored-results not really affected by AddNode,
##For UI: simply must store results of In.DF which defined nodes that 111 can borrow from (right now randomly generated by AddNode)
start_time <- Sys.time()
brw.Potential <- propagate$loan.backProp(ntwk, 111, algorithm ="NLOPT_GN_ISRES", browse = FALSE,
                                         controls = list(controls = list(xtol_rel = 0.1, xtol_abs = c(rep(0.1,2),0.01,0.01),
                                                                         relax = FALSE, maxeval = 1000,
                                                                         span = 0.5)))
end_time <- Sys.time()-start_time

#display result
##NOTE: Issue here is that as Node 111 has 750 of uncommitted capital, it can obviously always borrow >750
z.loess <- matrix(predict(brw.Potential$root.S, expand.grid(R = seq(1.01, 2.5,0.01), Z = seq(0.01, 099,0.01))),
                  length(seq(1.01, 2.5,0.01)), length(seq(0.01, 0.99,0.01)))
rgl::persp3d(seq(1.01, 2.5,0.01), seq(0.01, 0.99,0.01), z.loess, col = 'skyblue')

#Forward prop of loan by node X1
##NOTE: We choose borrow 865 (750+115) @ 42% collateral and 10% Interest
start_time <- Sys.time()
postBrw.ntwk <- propagate$loan.frwdProp(ntwk,111,brw.Potential$S.list,865,1.10,0.42,rLim=2.5)
end_time <- Sys.time()-start_time

#### Plot loan  ####
